# Generated by Django 5.1.4 on 2025-11-22 16:18

import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_add_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=procurement.models.attachment_upload_path),
        ),
    ]
