# Generated by Django 5.1.4 on 2025-11-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_add_externalurl_financecomment'),
        ('procurement', '0004_alter_attachment_file'),
    ]

    operations = [
    ]
