# Generated by Django 5.1.4 on 2025-11-25 06:34

import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_merge_20251122_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='receipt',
            field=models.URLField(blank=True, null=True),
        ),
    ]
